/**
 * Profile System Constants
 * Default data, colors, and static configurations
 */

// xport const MOVIES_DATA: Movie[] = [
//   {
//     id: 'planters-plantation',
//     title: 'The Planters Plantation',
//     image: 'https://i.ibb.co/BHbfNpkQ/planters-plantation.png',
//     year: 2022,
//     country: 'Cameroon',
//     genres: ['Drama', 'Musical'],
//     featured: false,
//     description:
//       'A historical drama about resistance, identity, and colonial legacy centered around a plantation inheritance struggle.',
//     duration: '2h 15m',
//     ageRating: '16+',
//     rating: 4.5,
//   },
//   {
//     id: 'saving-mbang',
//     title: 'Saving Mbang',
//     image: 'https://i.ibb.co/RGSygX9q/mbnag.png',
//     year: 2020,
//     country: 'Cameroon',
//     genres: ['Drama', 'Romance'],
//     featured: false,
//     description: 'A young man torn between family responsibility and love faces difficult choices that change his life.',
//     duration: '1h 50m',
//     ageRating: '13+',
//     rating: 4.6,
//   },
//   {
//     id: 'fishermans-diary',
//     title: "The Fisherman's Diary",
//     image: 'https://i.ibb.co/xTCfBL6/fdiary.png',
//     year: 2020,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: true,
//     description:
//       'A determined young girl pursues education against societal expectations while her fisherman father struggles to support her dreams.',
//     duration: '2h 25m',
//     ageRating: '13+',
//     director: 'Enah Johnscott',
//     writer: 'Enah Johnscott',
//     stars: 'Kang Quintus, Faith Fidel, Ndamo Damarise',
//     language: 'English',
//     subtitles: 'English, French',
//     rating: 4.8,
//   },
//   {
//     id: 'therapy',
//     title: 'Therapy',
//     image: 'https://i.ibb.co/DDk4rzpn/therapist.png',
//     year: 2020,
//     country: 'Cameroon',
//     genres: ['Drama', 'Psychological'],
//     featured: false,
//     description: 'A couple in emotional crisis seeks unconventional therapy to fix their collapsing relationship.',
//     duration: '1h 45m',
//     ageRating: '16+',
//     rating: 4.6,
//   },
//   {
//     id: 'half-heaven',
//     title: 'Half Heaven',
//     image: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
//     year: 2022,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A dramatic story exploring ambition, survival, and emotional conflict in urban Cameroon.',
//     rating: 4.4,
//   },
//   {
//     id: 'kuvah',
//     title: 'Kuvah',
//     image: 'https://i.ibb.co/Mk1v1nqw/kuva.png',
//     year: 2022,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A social drama centered on personal struggle and societal pressure in modern Cameroon.',
//     rating: 4.3,
//   },
//   {
//     id: 'a-man-for-the-weekend',
//     title: 'A Man for the Weekend',
//     image: 'https://i.ibb.co/LdkRVJSN/A-Man-for-the-Weekend.png',
//     year: 2017,
//     country: 'Cameroon',
//     genres: ['Comedy', 'Romance'],
//     featured: false,
//     description: 'A romantic comedy about mistaken identities and unexpected relationships.',
//     rating: 4.2,
//   },
//   {
//     id: 'breach-of-trust',
//     title: 'Breach of Trust',
//     image: 'https://i.ibb.co/V0JsWLhq/Breach-of-Trust.png',
//     year: 2017,
//     country: 'Cameroon',
//     genres: ['Drama', 'Crime'],
//     featured: false,
//     description: 'A story dealing with family conflict, betrayal, and emotional consequences.',
//     rating: 4.5,
//   },
//   {
//     id: 'apple-for-two',
//     title: 'Apple For Two',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2017,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A romantic drama exploring relationships and difficult life decisions.',
//     rating: 4.1,
//   },
//   {
//     id: 'broken',
//     title: 'Broken',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2019,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A couple struggles with emotional trauma and hidden truths in their relationship.',
//     rating: 4.7,
//   },
//   {
//     id: 'hidden-dreams',
//     title: 'Hidden Dreams',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2021,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A young person fights societal expectations to pursue personal ambitions.',
//     rating: 4.2,
//   },
//   {
//     id: 'love-trap',
//     title: 'Love Trap',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2022,
//     country: 'Cameroon',
//     genres: ['Romance', 'Drama'],
//     featured: false,
//     description: 'A love story complicated by deception, choices, and emotional conflict.',
//     rating: 4.0,
//   },
//   {
//     id: 'laxe-lourd',
//     title: "L'Axe Lourd",
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2023,
//     country: 'Cameroon',
//     genres: ['Action', 'Drama'],
//     featured: false,
//     description: 'A tense drama exploring life along a dangerous and strategic highway route.',
//     rating: 4.6,
//   },
//   {
//     id: 'muna-moto',
//     title: 'Muna Moto',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 1975,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A classic Cameroonian film exploring tradition, marriage, and societal pressure.',
//     rating: 4.9,
//   },
//   {
//     id: 'les-saignantes',
//     title: 'Les Saignantes',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2005,
//     country: 'Cameroon',
//     genres: ['Sci-Fi', 'Drama'],
//     featured: false,
//     description: 'A futuristic Cameroonian film blending political commentary and surreal storytelling.',
//     rating: 4.5,
//   },
//   {
//     id: 'sisters-in-law',
//     title: 'Sisters in Law',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2005,
//     country: 'Cameroon',
//     genres: ['Documentary'],
//     featured: false,
//     description: "A documentary following women working in Cameroon's justice system.",
//     rating: 4.8,
//   },
//   {
//     id: 'clando',
//     title: 'Clando',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 1996,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A political drama about identity, exile, and survival.',
//     rating: 4.4,
//   },
//   {
//     id: 'le-silence-de-la-foret',
//     title: 'Le Silence de la Forêt',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2003,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A powerful story about discrimination and marginalized communities.',
//     rating: 4.7,
//   },
//   {
//     id: 'moolaadé',
//     title: 'Moolaadé',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2004,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A woman protects girls from harmful traditions in a rural African community.',
//     rating: 4.9,
//   },
//   {
//     id: 'le-prix-de-la-liberte',
//     title: 'Le Prix de la Liberté',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 1978,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A historical drama about freedom and political struggle.',
//     rating: 4.6,
//   },
//   {
//     id: 'volcanic-sprint',
//     title: 'Volcanic Sprint',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2007,
//     country: 'Cameroon',
//     genres: ['Action'],
//     featured: false,
//     description: 'An action-driven story set against natural and social chaos.',
//     rating: 4.3,
//   },
//   {
//     id: 'nganu',
//     title: 'Nganù',
//     image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
//     year: 2023,
//     country: 'Cameroon',
//     genres: ['Drama'],
//     featured: false,
//     description: 'A modern Cameroonian drama exploring identity, survival, and society.',
//     rating: 4.7,

import {
  UserProfile,
  UserStats,
  UserPreferences,
  SubscriptionPlan,
  SecuritySettings,
  RecentlyWatched,
} from './types';

// Profile Colors
export const PROFILE_COLORS = {
  primary: '#CE1126', // Red
  secondary: '#FFFFFF', // White
  dark: '#0B0E14',
  darkAlt: '#0E121A',
  gray: '#6B7280',
  grayDark: '#1A1E26',
  success: '#10B981',
  warning: '#F59E0B',
} as const;

// Default Profile
export const DEFAULT_USER_PROFILE: UserProfile = {
  id: 'user-123',
  fullName: 'Sarah Anderson',
  email: 'sarah.anderson@example.com',
  phoneNumber: '+1 (555) 123-4567',
  avatar: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
  coverImage:
    'https://i.ibb.co/MDLDZTtf/sawa.png',
  bio: 'Movie and music enthusiast. Always exploring new content on Sawaflix.',
  joinDate: 'January 2024',
  region: 'North America',
  language: 'English',
  country: 'United States',
  isPremium: true,
};

// Default Stats
export const DEFAULT_USER_STATS: UserStats = {
  moviesWatched: 143,
  musicPlayed: 2847,
  watchlistItems: 28,
  downloads: 12,
};

// Default Preferences
export const DEFAULT_PREFERENCES: UserPreferences = {
  videoQuality: 'auto',
  subtitles: true,
  subtitleLanguage: 'English',
  autoplayNextEpisode: true,
  autoplayNextTrack: true,
  notificationsEnabled: true,
};

// Default Subscription
export const DEFAULT_SUBSCRIPTION: SubscriptionPlan = {
  id: 'sub-123',
  name: 'Premium',
  status: 'ACTIVE',
  startDate: 'January 15, 2024',
  renewalDate: 'February 15, 2024',
  price: 9.99,
  features: [
    'Ad-free streaming',
    '4K quality',
    'Download content',
    'Watch on 4 devices',
    'Enhanced recommendations',
    'Priority support',
  ],
  autoRenew: true,
};

// Default Security Settings
export const DEFAULT_SECURITY_SETTINGS: SecuritySettings = {
  passwordLastChanged: 'December 2023',
  twoFactorEnabled: true,
  activeSessions: [
    {
      id: 'session-1',
      device: 'MacBook Pro',
      browser: 'Chrome',
      location: 'New York, USA',
      lastActive: '5 minutes ago',
      isCurrent: true,
    },
    {
      id: 'session-2',
      device: 'iPhone 14',
      browser: 'Safari',
      location: 'New York, USA',
      lastActive: '2 hours ago',
      isCurrent: false,
    },
    {
      id: 'session-3',
      device: 'iPad Pro',
      browser: 'Safari',
      location: 'Los Angeles, USA',
      lastActive: '1 day ago',
      isCurrent: false,
    },
  ],
  lastLogin: 'Today at 9:45 AM',
};

// Default Recently Watched
export const DEFAULT_RECENTLY_WATCHED: RecentlyWatched[] = [
  {
    id: 'item-1',
    title: 'The Fisherman\'s Diary',
    type: 'movie',
    thumbnail: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    watchedDate: '2 hours ago',
    progress: 85,
    duration: '2h 15m',
  },
  {
    id: 'item-2',
    title: 'Cosmic Journey',
    type: 'music',
    thumbnail: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
    watchedDate: 'Yesterday',
    progress: 100,
    duration: '3:45',
  },
  {
    id: 'item-3',
    title: 'Urban Tales',
    type: 'movie',
    thumbnail: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
    watchedDate: '3 days ago',
    progress: 45,
    duration: '1h 50m',
  },
  {
    id: 'item-4',
    title: 'Midnight Sessions',
    type: 'music',
    thumbnail: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
    watchedDate: '1 week ago',
    progress: 100,
    duration: '4:12',
  },
  {
    id: 'item-5',
    title: 'Lost in Translation',
    type: 'movie',
    thumbnail: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
    watchedDate: '2 weeks ago',
    progress: 100,
    duration: '2h 02m',
  },
];

// Profile Menu Sections
export const PROFILE_MENU_SECTIONS = [
  { id: 'personal-info', label: 'Personal Information', icon: 'User' },
  { id: 'subscription', label: 'Subscription Plan', icon: 'CreditCard' },
  { id: 'preferences', label: 'Viewing Preferences', icon: 'Settings' },
  { id: 'security', label: 'Security', icon: 'Lock' },
  { id: 'recently-watched', label: 'Recently Watched', icon: 'Clock' },
  { id: 'downloads', label: 'Downloads', icon: 'Download' },
  { id: 'help', label: 'Help & Support', icon: 'HelpCircle' },
] as const;
