export async function getCreatorContent() {
  return [
    {
      id: "1",
      title: "Night Chase",
      description: "An adrenaline-pumping high-speed pursuit through the city.",
      thumbnail: "/images/content/night_chase.png",
      type: "movie",
      views: 12400,
      status: "approved",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    },
    {
      id: "2",
      title: "Acoustic Dreams",
      description: "Melodic guitar compositions for soulful relaxation.",
      thumbnail: "/images/content/acoustic_dreams.png",
      type: "music",
      views: 8300,
      status: "draft",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    },
    {
      id: "3",
      title: "Mystery Tales",
      description: "Explore the dark secrets of the unknown.",
      thumbnail: "/images/content/mystery_tales.png",
      type: "story",
      views: 5100,
      status: "pending",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    },
    {
      id: "4",
      title: "Urban Beats",
      description: "Modern street music and urban culture.",
      thumbnail: "/images/content/urban_beats.png",
      type: "music",
      views: 3700,
      status: "approved",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    },
    {
      id: "5",
      title: "Forgotten Journey",
      description: "A lost path through ancient lands.",
      thumbnail: "/images/content/forgotten_journey.png",
      type: "movie",
      views: 1900,
      status: "draft",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    },
    {
      id: "6",
      title: "Haunted Manor",
      description: "A chilling tale of a house that never sleeps.",
      thumbnail: "/images/content/haunted_manor.png",
      type: "story",
      views: 920,
      status: "pending",
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    },
  ];
}