/**
 * Movie Page Constants
 */

import { Movie } from './types';

export const FILTERS = ['All', 'Action', 'Comedy', 'Drama', 'Romance', 'Sci-Fi', 'Documentary'];

export const MOVIES_DATA: Movie[] = [
  {
    id: 'planters-plantation',
    title: 'The Planters Plantation',
    image: 'https://i.ibb.co/BHbfNpkQ/planters-plantation.png',
    year: 2022,
    country: 'Cameroon',
    genres: ['Drama', 'Musical'],
    featured: false,
    description:
      'A historical drama about resistance, identity, and colonial legacy centered around a plantation inheritance struggle.',
    duration: '2h 15m',
    ageRating: '16+',
    rating: 4.5,
  },
  {
    id: 'saving-mbang',
    title: 'Saving Mbang',
    image: 'https://i.ibb.co/RGSygX9q/mbnag.png',
    year: 2020,
    country: 'Cameroon',
    genres: ['Drama', 'Romance'],
    featured: false,
    description: 'A young man torn between family responsibility and love faces difficult choices that change his life.',
    duration: '1h 50m',
    ageRating: '13+',
    rating: 4.6,
  },
  {
    id: 'fishermans-diary',
    title: "The Fisherman's Diary",
    image: 'https://i.ibb.co/xTCfBL6/fdiary.png',
    year: 2020,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: true,
    description:
      'A determined young girl pursues education against societal expectations while her fisherman father struggles to support her dreams.',
    duration: '2h 25m',
    ageRating: '13+',
    director: 'Enah Johnscott',
    writer: 'Enah Johnscott',
    stars: 'Kang Quintus, Faith Fidel, Ndamo Damarise',
    language: 'English',
    subtitles: 'English, French',
    rating: 4.8,
  },
  {
    id: 'therapy',
    title: 'Therapy',
    image: 'https://i.ibb.co/DDk4rzpn/therapist.png',
    year: 2020,
    country: 'Cameroon',
    genres: ['Drama', 'Psychological'],
    featured: false,
    description: 'A couple in emotional crisis seeks unconventional therapy to fix their collapsing relationship.',
    duration: '1h 45m',
    ageRating: '16+',
    rating: 4.6,
  },
  {
    id: 'half-heaven',
    title: 'Half Heaven',
    image: 'https://i.ibb.co/T6kBJq0/half-Heaven.png',
    year: 2022,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A dramatic story exploring ambition, survival, and emotional conflict in urban Cameroon.',
    rating: 4.4,
  },
  {
    id: 'kuvah',
    title: 'Kuvah',
    image: 'https://i.ibb.co/Mk1v1nqw/kuva.png',
    year: 2022,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A social drama centered on personal struggle and societal pressure in modern Cameroon.',
    rating: 4.3,
  },
  {
    id: 'a-man-for-the-weekend',
    title: 'A Man for the Weekend',
    image: 'https://i.ibb.co/LdkRVJSN/A-Man-for-the-Weekend.png',
    year: 2017,
    country: 'Cameroon',
    genres: ['Comedy', 'Romance'],
    featured: false,
    description: 'A romantic comedy about mistaken identities and unexpected relationships.',
    rating: 4.2,
  },
  {
    id: 'breach-of-trust',
    title: 'Breach of Trust',
    image: 'https://i.ibb.co/V0JsWLhq/Breach-of-Trust.png',
    year: 2017,
    country: 'Cameroon',
    genres: ['Drama', 'Crime'],
    featured: false,
    description: 'A story dealing with family conflict, betrayal, and emotional consequences.',
    rating: 4.5,
  },
  {
    id: 'apple-for-two',
    title: 'Apple For Two',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2017,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A romantic drama exploring relationships and difficult life decisions.',
    rating: 4.1,
  },
  {
    id: 'broken',
    title: 'Broken',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2019,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A couple struggles with emotional trauma and hidden truths in their relationship.',
    rating: 4.7,
  },
  {
    id: 'hidden-dreams',
    title: 'Hidden Dreams',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2021,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A young person fights societal expectations to pursue personal ambitions.',
    rating: 4.2,
  },
  {
    id: 'love-trap',
    title: 'Love Trap',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2022,
    country: 'Cameroon',
    genres: ['Romance', 'Drama'],
    featured: false,
    description: 'A love story complicated by deception, choices, and emotional conflict.',
    rating: 4.0,
  },
  {
    id: 'laxe-lourd',
    title: "L'Axe Lourd",
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2023,
    country: 'Cameroon',
    genres: ['Action', 'Drama'],
    featured: false,
    description: 'A tense drama exploring life along a dangerous and strategic highway route.',
    rating: 4.6,
  },
  {
    id: 'muna-moto',
    title: 'Muna Moto',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 1975,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A classic Cameroonian film exploring tradition, marriage, and societal pressure.',
    rating: 4.9,
  },
  {
    id: 'les-saignantes',
    title: 'Les Saignantes',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2005,
    country: 'Cameroon',
    genres: ['Sci-Fi', 'Drama'],
    featured: false,
    description: 'A futuristic Cameroonian film blending political commentary and surreal storytelling.',
    rating: 4.5,
  },
  {
    id: 'sisters-in-law',
    title: 'Sisters in Law',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2005,
    country: 'Cameroon',
    genres: ['Documentary'],
    featured: false,
    description: "A documentary following women working in Cameroon's justice system.",
    rating: 4.8,
  },
  {
    id: 'clando',
    title: 'Clando',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 1996,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A political drama about identity, exile, and survival.',
    rating: 4.4,
  },
  {
    id: 'le-silence-de-la-foret',
    title: 'Le Silence de la Forêt',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2003,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A powerful story about discrimination and marginalized communities.',
    rating: 4.7,
  },
  {
    id: 'moolaadé',
    title: 'Moolaadé',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2004,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A woman protects girls from harmful traditions in a rural African community.',
    rating: 4.9,
  },
  {
    id: 'le-prix-de-la-liberte',
    title: 'Le Prix de la Liberté',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 1978,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A historical drama about freedom and political struggle.',
    rating: 4.6,
  },
  {
    id: 'volcanic-sprint',
    title: 'Volcanic Sprint',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2007,
    country: 'Cameroon',
    genres: ['Action'],
    featured: false,
    description: 'An action-driven story set against natural and social chaos.',
    rating: 4.3,
  },
  {
    id: 'nganu',
    title: 'Nganù',
    image: 'https://i.ibb.co/MDLDZTtf/sawa.png',
    year: 2023,
    country: 'Cameroon',
    genres: ['Drama'],
    featured: false,
    description: 'A modern Cameroonian drama exploring identity, survival, and society.',
    rating: 4.7,
  },
];
