import { Musician } from '../../types/profile';

export const GENRE_FILTERS = ['All', 'Bikutsi', 'Makossa', 'Bend Skin', 'Afrobeat', 'Hip-Hop', 'R&B', 'Traditional', 'Gospel'];

export const ERA_FILTERS = ['All', '1960s-1980s', '1990s-2000s', '2010s', '2020s'];

export const MUSICIANS_DATA: Musician[] = [
  {
    id: 'manu-dibango',
    name: 'Manu Dibango',
    image: '/artists/dibango.jpg',
    born: 1933,
    died: 2020,
    country: 'Cameroon',
    genres: ['Makossa', 'Jazz', 'Funk'],
    featured: true,
    description: 'Legendary saxophonist and pioneer of Makossa music, famous for the global hit "Soul Makossa".',
    topSongs: ['Soul Makossa', 'Waka Juju', 'Big Blow'],
    awards: ['Grammy Lifetime Achievement Award', "Commandeur de l'Ordre des Arts et des Lettres"],
    rating: 4.9,
  },
  {
    id: 'richard-bona',
    name: 'Richard Bona',
    image: '/artists/richardbonajazz.jpg',
    year: 1967,
    country: 'Cameroon',
    genres: ['Jazz', 'Afrobeat', 'World'],
    featured: true,
    description: 'Internationally acclaimed bassist, composer, and multi-instrumentalist known for his virtuosic playing.',
    topSongs: ['Dibango', 'Te Misea', 'Ekwa Mwato'],
    awards: ['Multiple Grammy Nominations', 'Kora Award'],
    rating: 4.9,
  },
  {
    id: 'petit-pays',
    name: 'Petit Pays',
    image: '/artists/petipays.jpg',
    born: 1965,
    country: 'Cameroon',
    genres: ['Makossa', 'Bikutsi'],
    featured: true,
    description: 'Iconic singer known for blending Makossa with modern sounds and his flamboyant style.',
    topSongs: ['Travail', 'Le Sage', 'Emma'],
    rating: 4.7,
  },
  {
    id: 'charlotte-dipanda',
    name: 'Charlotte Dipanda',
    image: '/artists/charlottedipanda.jpg',
    born: 1985,
    country: 'Cameroon',
    genres: ['Bikutsi', 'Afro-soul', 'R&B'],
    featured: true,
    description: 'Powerful vocalist known for emotional ballads and modern Bikutsi interpretations.',
    topSongs: ["Elle m'a dit", 'Massako', 'Un Jour'],
    awards: ['Best Female Artist - Canal 2\'Or'],
    rating: 4.8,
  },
  {
    id: 'fally-ipupa-cameroon',
    name: 'Fally Ipupa',
    image: 'https://i.ibb.co/placeholder/fally-ipupa.png',
    born: 1977,
    country: 'Democratic Republic of Congo',
    genres: ['Ndombolo', 'Rumba', 'Afrobeat'],
    featured: false,
    description: 'Note: While Congolese, Fally Ipupa is immensely popular across Cameroon and Central Africa.',
    topSongs: ['Eloko Oyo', 'Original', 'Message'],
    rating: 4.8,
  },
  {
    id: 'krotal',
    name: 'Krotal',
    image: 'https://i.ibb.co/placeholder/krotal.png',
    born: 1983,
    country: 'Cameroon',
    genres: ['Bikutsi', 'Bend Skin'],
    featured: false,
    description: 'High-energy performer known for modern Bikutsi and danceable hits.',
    topSongs: ['Vieux Kamer', 'Le Chemin', 'Hommage'],
    rating: 4.5,
  },
  {
    id: 'tenor',
    name: 'Tenor',
    image: 'https://i.ibb.co/placeholder/tenor.png',
    born: 1986,
    country: 'Cameroon',
    genres: ['Hip-Hop', 'Rap'],
    featured: false,
    description: 'Influential Cameroonian rapper addressing social issues and urban life.',
    topSongs: ['L\'argent', 'Mon Pays', 'La Danse'],
    rating: 4.6,
  },
  {
    id: 'magasco',
    name: 'Magasco',
    image: 'https://i.ibb.co/placeholder/magasco.png',
    born: 1989,
    country: 'Cameroon',
    genres: ['Bikutsi', 'Afrobeat', 'Dancehall'],
    featured: false,
    description: 'Dynamic singer blending traditional rhythms with modern Afrobeat.',
    topSongs: ['Jubilation', 'Ma Girl', 'Omana'],
    rating: 4.4,
  },
  {
    id: 'mimie',
    name: 'Mimie',
    image: 'https://i.ibb.co/placeholder/mimie.png',
    born: 1985,
    country: 'Cameroon',
    genres: ['Bikutsi', 'Pop'],
    featured: false,
    description: 'Popular female vocalist known for energetic Bikutsi performances.',
    topSongs: ['Mets Moi Au Courant', 'Mama Africa', 'Bikut-si'],
    rating: 4.6,
  },
  {
    id: 'wandim',
    name: 'Wandim',
    image: 'https://i.ibb.co/placeholder/wandim.png',
    born: 1988,
    country: 'Cameroon',
    genres: ['Bend Skin', 'Afrobeat'],
    featured: false,
    description: 'Young artist modernizing Bend Skin music for contemporary audiences.',
    topSongs: ['Kamer', 'Mon Amour', 'Africa'],
    rating: 4.3,
  },
  {
    id: 'x-maleya',
    name: 'X-Maleya',
    image: 'https://i.ibb.co/placeholder/x-maleya.png',
    formed: 2005,
    country: 'Cameroon',
    genres: ['Makossa', 'R&B', 'Afrobeat'],
    featured: false,
    description: 'Popular music group known for romantic ballads and dance hits.',
    topSongs: ['Moi Je T\'aime', 'Marlène', 'Parce Que'],
    rating: 4.7,
  },
  {
    id: 'blanche-bailey',
    name: 'Blanche Bailly',
    image: 'https://i.ibb.co/placeholder/blanche-bailey.png',
    born: 1990,
    country: 'Cameroon',
    genres: ['Afrobeat', 'R&B', 'Pop'],
    featured: false,
    description: 'Rising star with smooth vocals and contemporary Afro-pop sound.',
    topSongs: ['Ton Pied', 'Argent', 'Mêmes Mêmes'],
    rating: 4.5,
  },
  {
    id: 'locko',
    name: 'Locko',
    image: 'https://i.ibb.co/placeholder/locko.png',
    born: 1990,
    country: 'Cameroon',
    genres: ['R&B', 'Afrobeat'],
    featured: false,
    description: 'Soulful singer known for romantic tracks and smooth vocals.',
    topSongs: ['Let Go', 'Mama', 'Bonne Année'],
    rating: 4.4,
  },
  {
    id: 'ko-cee',
    name: 'Ko-C',
    image: 'https://i.ibb.co/placeholder/ko-cee.png',
    born: 1988,
    country: 'Cameroon',
    genres: ['Hip-Hop', 'Rap'],
    featured: false,
    description: 'Pioneering female rapper addressing gender and social issues.',
    topSongs: ['Who Know', 'Ndolo', 'African Girl'],
    rating: 4.5,
  },
  {
    id: 'sam-fan-ngo',
    name: 'Sam Fan Thomas',
    image: 'https://i.ibb.co/placeholder/sam-fan-thomas.png',
    born: 1952,
    country: 'Cameroon',
    genres: ['Makossa'],
    featured: false,
    description: 'Makossa legend famous for the hit "African Typic Collection".',
    topSongs: ['African Typic Collection', 'Ewondo', 'Ngando'],
    rating: 4.8,
  },
  {
    id: 'prince-ekodi',
    name: 'Prince Ekodi',
    image: 'https://i.ibb.co/placeholder/prince-ekodi.png',
    born: 1965,
    country: 'Cameroon',
    genres: ['Makossa', 'Soukous'],
    featured: false,
    description: 'Veteran singer known for romantic Makossa songs.',
    topSongs: ['Mina', 'Princesse', 'Moi Je T\'aime'],
    rating: 4.6,
  },
  {
    id: 'grace-decca',
    name: 'Grace Decca',
    image: 'https://i.ibb.co/placeholder/grace-decca.png',
    born: 1946,
    country: 'Cameroon',
    genres: ['Bikutsi'],
    featured: false,
    description: 'Pioneering female Bikutsi musician who paved the way for women in Cameroonian music.',
    topSongs: ['Nga Nga Nga', 'Mbo Mbo', 'Ndeme'],
    rating: 4.7,
  },
  {
    id: 'anne-marie-ndzié',
    name: 'Anne-Marie Nzié',
    image: 'https://i.ibb.co/placeholder/anne-marie-ndzie.png',
    born: 1932,
    died: 2016,
    country: 'Cameroon',
    genres: ['Bikutsi'],
    featured: false,
    description: 'Legendary Bikutsi singer known as the "Queen of Bikutsi".',
    topSongs: ['Bikutsi Si', 'Mouan Ja', 'Bamoun'],
    rating: 4.9,
  },
  {
    id: 'les-têtes-brulées',
    name: 'Les Têtes Brûlées',
    image: 'https://i.ibb.co/placeholder/les-tetes-brulees.png',
    formed: 1987,
    country: 'Cameroon',
    genres: ['Bikutsi', 'Rock'],
    featured: false,
    description: 'Revolutionary band that electrified Bikutsi and brought it to international audiences.',
    topSongs: ['Mets Mets', 'M\'ongele M\'am', 'Mona Mona'],
    rating: 4.8,
  },
  {
    id: 'ekambi-brillant',
    name: 'Ekambi Brillant',
    image: 'https://i.ibb.co/placeholder/ekambi-brillant.png',
    born: 1948,
    country: 'Cameroon',
    genres: ['Makossa'],
    featured: false,
    description: 'Veteran Makossa artist known for social commentary through music.',
    topSongs: ['Ngon\'a Mba', 'Ewala', 'Musa'],
    rating: 4.7,
  },
];

export const FEATURED_MUSICIANS = MUSICIANS_DATA.filter(musician => musician.featured);